### ISSUE TITLE
AO-85 has disappeared from SatSat

### ISSUE THREAD

**Issue by burnsfisher** [akhenakh/satsattransponder#1]
Hi...not sure if the Satsat author is still active, so I'll try posting this in several places.  AO-85 has been turned off for a few months but is active again.  Apparently during those months off Satsat decided to stop updating it, so the predictions for AO-85 are no longer there.  

AO-85, whose keps are available on Amsat.org, should continue to be updated.

Thanks!

**Comment by akhenakh** [comment]
SatSat is using public data for TLE updates, maybe the amsat URL changed ?

**Comment by burnsfisher** [comment]
Thanks for responding.  I don't know what URL Satsat is looking at, but
AMSAT's nasabare tle list is at
https://www.amsat.org/tle/current/nasabare.txt  .  I just checked and it
does have AO-85.  How can I help you figure this out?

73, Burns WB1FJ

**Comment by akhenakh** [comment]
solved by fixing upstream data

**Comment by burnsfisher** [comment]
Thank you!

**Comment by Erynys** [comment]
I just updated TLE data and now can’t track satellite now. All other sats are fine updating, that I can see

**Comment by Erynys** [comment]
I just updated TLE data and now can’t track satellite now all data null All other sats are fine updating, that I can see
